=== ishaqmarashy/XML-Database/XMLDB/FlightDBSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Airline">
 	<xs:complexType >
  		<xs:sequence>
     		 <xs:element name="Passenger" type="Person" minOccurs="0" maxOccurs="unbounded"/>
    		 <xs:element name="Employee" type="Employee" minOccurs="1" maxOccurs="unbounded"/>
     		 <xs:element name="Pilot" type="Pilot" minOccurs="1" maxOccurs="unbounded"/>
     		 <xs:element name="Fare" type="Fare" minOccurs="0" maxOccurs="unbounded"/>
     		 <xs:element name="Flight" type="Flight" minOccurs="0" maxOccurs="unbounded"/>
     		 <xs:element name="Department" type="Department" minOccurs="1" maxOccurs="unbounded"/>
   		 </xs:sequence>
   		  	<xs:attribute name="AirlineName"/>
  	</xs:complexType>
  	<xs:key name="PassengerKey"><!-- Passenger aka Person has a unique ID so we declare an index for it-->
		<xs:selector xpath="Airline/Passenger"/>
		<xs:field xpath="@ID"/>
	</xs:key>
	<xs:keyref name="PassengerRef" refer="PassengerKey"><!-- Ticket has a reference to a passengers ID-->
	<xs:selector xpath="Airline/Flight/Ticket"/>
	<xs:field xpath="@PassengerID"/>
	</xs:keyref>
	
  	<xs:key name="EmployeeKey">
		<xs:selector xpath="Airline/Employee"/><!-- Employee extends person therefore also has a unique ID -->
		<xs:field xpath="@ID"/>
	</xs:key>
	<xs:keyref name="EmployeeRef" refer="EmployeeKey"><!-- Employee has a supervisor that references another employee -->
		<xs:selector xpath="Airline/Employee"/>
		<xs:field xpath="@Supervisor"/>
	</xs:keyref>
	
	 <xs:key name="DepartmentKey"><!-- Each Department in an airline has a unique department code -->
		<xs:selector xpath="Airline/Department"/>
		<xs:field xpath="@Code"/>
	</xs:key>
	<xs:keyref name="DepartmentRef" refer="DepartmentKey"> <!-- Each Employee has a reference to the department they work in -->
		<xs:selector xpath="Airline/Employee"/>
		<xs:field xpath="@DepartmentID"/>
	</xs:keyref>
	
	<xs:keyref name="CrewRef" refer="EmployeeKey"><!-- A flight holds references to employees that are crew -->
		<xs:selector xpath="Airline/Flight"/>
		<xs:field xpath="@Crew"/>
	</xs:keyref>
	
	
	<xs:key name="PilotKey"><!-- A Pilot Extends an employee therefore also has an unique ID -->
		<xs:selector xpath="Airline/Pilot"/>
		<xs:field xpath="@ID"/>
	</xs:key>
	<xs:keyref name="PilotRef" refer="PilotKey"><!-- A flight holds references to their pilots -->
		<xs:selector xpath="Airline/Flight"/>
		<xs:field xpath="@Pilot"/>
	</xs:keyref>
	
	<xs:key name="FareKey"><!-- Each Fare has a Unique Fare Type -->
		<xs:selector xpath="Airline/Fare"/>
		<xs:field xpath="@FareType"/>
	</xs:key>
	<xs:keyref name="FareRef" refer="FareKey"><!-- Each Ticket has a reference to a fare -->
		<xs:selector xpath="Airline/Flight/Ticket"/>
		<xs:field xpath="@FareType"/>
	</xs:keyref>
  </xs:element>
  
  <xs:simpleType name="name"><!-- Used to limit noun type inputs to include characters a to Z in addition to special characters (' ','.','-') -->
    <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z. -]{2,50}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="ssn"><!-- Regular to restrict SSN input to XXX-XX-XXXX format -->
    <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}"/>
    </xs:restriction>
  </xs:simpleType>
           
  <xs:complexType name="Person"><!-- Acts as the Passenger in an airline and a Parent to Employee -->
    <xs:sequence>
      <xs:element name="FirstName" type="name"/>
      <xs:element name="LastName" type="name"/>
      <xs:element name="DateOfBirth" type="xs:date"/>
      <xs:element name="Nationality" type="name"/>
      <xs:element name="PassportNumber" type="xs:string"/>   
    </xs:sequence>
    <xs:attribute name="ID" type="xs:ID"  use="required"/> <!-- PK -->
  </xs:complexType>
  
  <xs:complexType name="Employee"><!-- Additional Details required for an employee -->
	<xs:complexContent>
	      <xs:extension base="Person">
	        <xs:sequence>
 			<xs:element name="Salary">
 				<xs:simpleType>
    			<xs:restriction base="xs:positiveInteger">
     				<xs:minInclusive value="1000"/>
      				<xs:maxInclusive value="1000000"/>
    		  	</xs:restriction>
  			  </xs:simpleType>
  			  </xs:element>
	          <xs:element name="StartDate" type="xs:date"/>
	          <xs:element name="SSN" type="ssn"/><!-- Make special data type -->
	        </xs:sequence>
	     	   <xs:attribute name="Supervisor" type="xs:IDREF"/><!-- Employee references their supervisor (FK)-->
	           <xs:attribute name="DepartmentID" type="xs:IDREF"  use="required"/><!-- Employee references the department(FK) they work in  -->
	      </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="Pilot"><!-- Pilot is a child to an employee -->
	<xs:complexContent>
	      <xs:extension base="Employee">
	        <xs:sequence>       
	          <xs:element name="DateOfIssue" type="xs:date"/>
	        </xs:sequence>
	        <xs:attribute name="CertificateNumber" type="xs:positiveInteger"  use="required"/><!-- Each pilot has a license (PK)-->
	      </xs:extension>
	</xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="Department"><!-- Employees work in a department -->
    <xs:sequence>
      <xs:element name="Name" type="name"/>
    </xs:sequence>
    <xs:attribute name="Manager" type="xs:IDREF"  use="required"/><!-- A Department holds a reference to its manager(FK) -->
    <xs:attribute name="Code" type="xs:ID"  use="required"/><!-- A department has a unique code(PK) to it -->
  </xs:complexType>
  
  <xs:complexType name="Ticket"><!-- Each Flight Holds its tickets -->
     <xs:sequence>
       <xs:element name="SeatNumber" type="xs:positiveInteger"/>
	</xs:sequence>
    <xs:attribute name="PassengerID" type="xs:IDREF"  use="required"/><!-- a ticket holds a reference to its passengers ID -->
    <xs:attribute name="FareType" type="xs:IDREF"  use="required"/><!-- a ticket holds a reference to the fare paid -->
  </xs:complexType>
  
  <xs:complexType name="Fare">
    <xs:sequence>
      <xs:element name="Fare" type="xs:positiveInteger"/>
      <xs:element name="FareName" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="FareType" type="xs:ID"  use="required"/>
  </xs:complexType>
  
  <xs:complexType name="Flight">
    <xs:sequence>
      <xs:element name="Pilot" type="xs:IDREF" minOccurs="1" maxOccurs="unbounded"/><!-- A flight holds references to its pilots -->
      <xs:element name="Crew" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded"/><!-- A flight holds references to its pilots -->
      <xs:element name="DepartureTime" type="xs:dateTime"/>
      <xs:element name="ArrivalTime" type="xs:dateTime"/>
      <xs:element name="Source" type="name"/>
      <xs:element name="Destination" type="name" />
      <xs:element name="Ticket" type="Ticket" minOccurs="0" maxOccurs="unbounded"/> <!-- A Flight holds all tickets belonging to that flight -->
    </xs:sequence>
   	 <xs:attribute name="FlightCode" type="xs:ID" use="required"/>   <!--  each flight has its on ID(PK) -->
  </xs:complexType>
</xs:schema>

=== ishaqmarashy/XML-Database/XMLDB/FlightDB2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="FlightDBStylesheet-ISHAQ.xsl"?>
<Airline
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="FlightDBSchema.xsd " AirlineName="My Airline">
    <Passenger ID="_1">
        <FirstName>Dorris</FirstName>
        <LastName>Christiansen</LastName>
        <DateOfBirth>1980-08-17</DateOfBirth>
        <Nationality>Portugal</Nationality>
        <PassportNumber>815</PassportNumber>
    </Passenger>
    <Passenger ID="_2">
        <FirstName>Alvera</FirstName>
        <LastName>Ziemann</LastName>
        <DateOfBirth>2006-01-25</DateOfBirth>
        <Nationality>Bolivia</Nationality>
        <PassportNumber>441</PassportNumber>
    </Passenger>
    <Passenger ID="_3">
        <FirstName>Lonzo</FirstName>
        <LastName>Schmeler</LastName>
        <DateOfBirth>2003-10-28</DateOfBirth>
        <Nationality>Jordan</Nationality>
        <PassportNumber>274</PassportNumber>
    </Passenger>
    <Passenger ID="_4">
        <FirstName>Elijah</FirstName>
        <LastName>Walter</LastName>
        <DateOfBirth>2003-09-02</DateOfBirth>
        <Nationality>Wake Island</Nationality>
        <PassportNumber>79</PassportNumber>
    </Passenger>
    <Passenger ID="_6">
        <FirstName>Destany</FirstName>
        <LastName>Upton</LastName>
        <DateOfBirth>2017-11-08</DateOfBirth>
        <Nationality>Sierra Leone</Nationality>
        <PassportNumber>119</PassportNumber>
    </Passenger>
    <Passenger ID="_10">
        <FirstName>Gustave</FirstName>
        <LastName>Kohler</LastName>
        <DateOfBirth>2013-07-11</DateOfBirth>
        <Nationality>Denmark</Nationality>
        <PassportNumber>921</PassportNumber>
    </Passenger>
    <Passenger ID="_31">
        <FirstName>Alana</FirstName>
        <LastName>Kirlin</LastName>
        <DateOfBirth>2014-12-18</DateOfBirth>
        <Nationality>Guatemala</Nationality>
        <PassportNumber>239</PassportNumber>
    </Passenger>
    <Passenger ID="_32">
        <FirstName>Jeanne</FirstName>
        <LastName>Predovic</LastName>
        <DateOfBirth>1997-10-17</DateOfBirth>
        <Nationality>UnitedStates</Nationality>
        <PassportNumber>288</PassportNumber>
    </Passenger>
    <Passenger ID="_33">
        <FirstName>Francis</FirstName>
        <LastName>Crooks</LastName>
        <DateOfBirth>2015-03-18</DateOfBirth>
        <Nationality>Haiti</Nationality>
        <PassportNumber>549</PassportNumber>
    </Passenger>
    <Passenger ID="_34">
        <FirstName>Ignatius</FirstName>
        <LastName>Glover</LastName>
        <DateOfBirth>1995-05-30</DateOfBirth>
        <Nationality>Taiwan</Nationality>
        <PassportNumber>761</PassportNumber>
    </Passenger>
    <Passenger ID="_35">
        <FirstName>Nona</FirstName>
        <LastName>Gaylord</LastName>
        <DateOfBirth>2005-08-07</DateOfBirth>
        <Nationality>Vanuatu</Nationality>
        <PassportNumber>26</PassportNumber>
    </Passenger>
    <Passenger ID="_36">
        <FirstName>Gerard</FirstName>
        <LastName>Gibson</LastName>
        <DateOfBirth>2017-12-30</DateOfBirth>
        <Nationality>Singapore</Nationality>
        <PassportNumber>859</PassportNumber>
    </Passenger>
    <Employee ID="_37" Supervisor="_9" DepartmentID="_13">
        <FirstName>Colton</FirstName>
        <LastName>Considine</LastName>
        <DateOfBirth>1990-07-06</DateOfBirth>
        <Nationality>Bangladesh</Nationality>
        <PassportNumber>759</PassportNumber>
        <Salary>281223</Salary>
        <StartDate>2007-02-17</StartDate>
        <SSN>164-55-4210</SSN>
    </Employee>
    <Employee ID="_39" Supervisor="_9" DepartmentID="_13">
        <FirstName>Bridget</FirstName>
        <LastName>Lockman</LastName>
        <DateOfBirth>1995-05-03</DateOfBirth>
        <Nationality>Nigeria</Nationality>
        <PassportNumber>247</PassportNumber>
        <Salary>210315</Salary>
        <StartDate>1998-03-12</StartDate>
        <SSN>226-06-0050</SSN>
    </Employee>
    <Employee ID="_40" Supervisor="_9" DepartmentID="_13">
        <FirstName>Wilson</FirstName>
        <LastName>Abbott</LastName>
        <DateOfBirth>1991-11-18</DateOfBirth>
        <Nationality>Pakistan</Nationality>
        <PassportNumber>291</PassportNumber>
        <Salary>21697</Salary>
        <StartDate>2005-06-11</StartDate>
        <SSN>290-90-0602</SSN>
    </Employee>
    <Employee ID="_41" Supervisor="_9" DepartmentID="_13">
        <FirstName>Ruby</FirstName>
        <LastName>Kessler</LastName>
        <DateOfBirth>1996-06-07</DateOfBirth>
        <Nationality>Malaysia</Nationality>
        <PassportNumber>405</PassportNumber>
        <Salary>473205</Salary>
        <StartDate>1992-01-20</StartDate>
        <SSN>300-93-0009</SSN>
    </Employee>
    <Employee ID="_9" Supervisor="_1" DepartmentID="_12">
        <FirstName>Gunnar</FirstName>
        <LastName>Von</LastName>
        <DateOfBirth>2014-06-15</DateOfBirth>
        <Nationality>U.S.MinorOutlyingIslands</Nationality>
        <PassportNumber>755</PassportNumber>
        <Salary>792371</Salary>
        <StartDate>2000-08-11</StartDate>
        <SSN>070-10-0095</SSN>
    </Employee>
    <Employee ID="_5"  Supervisor="_9" DepartmentID="_13">
        <FirstName>Rhoda</FirstName>
        <LastName>Kohler</LastName>
        <DateOfBirth>1984-07-12</DateOfBirth>
        <Nationality>Yemen</Nationality>
        <PassportNumber>227</PassportNumber>
        <Salary>47774</Salary>
        <StartDate>2014-02-24</StartDate>
        <SSN>120-10-0007</SSN>
    </Employee>
    <Pilot ID="_8" CertificateNumber="81" Supervisor="_8" DepartmentID="_14">
        <FirstName>Gustave</FirstName>
        <LastName>Kohler</LastName>
        <DateOfBirth>2013-07-11</DateOfBirth>
        <Nationality>Denmark</Nationality>
        <PassportNumber>921</PassportNumber>
        <Salary>949854</Salary>
        <StartDate>2003-11-28</StartDate>
        <SSN>000-27-0000</SSN>
        <DateOfIssue>1996-10-31</DateOfIssue>
    </Pilot>
    <Pilot ID="_7" CertificateNumber="41" Supervisor="_8" DepartmentID="_14">
        <FirstName>Grace</FirstName>
        <LastName>Sanford</LastName>
        <DateOfBirth>1980-12-04</DateOfBirth>
        <Nationality>Indonesia</Nationality>
        <PassportNumber>297</PassportNumber>
        <Salary>222837</Salary>
        <StartDate>2007-07-04</StartDate>
        <SSN>000-58-2000</SSN>
        <DateOfIssue>1995-10-31</DateOfIssue>
    </Pilot>
    <Fare FareType="_21">
        <Fare>1000</Fare>
        <FareName>Economy</FareName>
    </Fare>
    <Fare FareType="_22">
        <Fare>1200</Fare>
        <FareName>Business</FareName>
    </Fare>
    <Fare FareType="_23">
        <Fare>1400</Fare>
        <FareName>First</FareName>
    </Fare>
    <Fare FareType="_24">
        <Fare>1600</Fare>
        <FareName>VIP</FareName>
    </Fare>
    <Flight FlightCode="F1">
        <Pilot>_8</Pilot>
        <Crew>_9</Crew>
        <DepartureTime>2012-06-30T19:00:00</DepartureTime>
        <ArrivalTime>2012-06-01T23:00:00</ArrivalTime>
        <Source>Dubai</Source>
        <Destination>United States</Destination>
        <Ticket PassengerID="_1"  FareType="_24">
            <SeatNumber>1</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_6" FareType="_21">
            <SeatNumber>2</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_4"  FareType="_21">
            <SeatNumber>3</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_3" FareType="_22">
            <SeatNumber>4</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_2" FareType="_22">
            <SeatNumber>5</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_1" FareType="_23">
            <SeatNumber>6</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_4" FareType="_23">
            <SeatNumber>7</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_3"  FareType="_24">
            <SeatNumber>8</SeatNumber>
        </Ticket>
    </Flight>
    <Flight FlightCode="F2">
        <Pilot>_8</Pilot>
        <Pilot>_7</Pilot>
        <Crew>_9</Crew>
        <Crew>_37</Crew>
        <Crew>_41</Crew>
        <DepartureTime>2012-06-30T19:00:00</DepartureTime>
        <ArrivalTime>2012-06-01T23:00:00</ArrivalTime>
        <Source>Dubai</Source>
        <Destination>Tanzania</Destination>
        <Ticket PassengerID="_1"  FareType="_24">
            <SeatNumber>1</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_6" FareType="_21">
            <SeatNumber>2</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_4"  FareType="_21">
            <SeatNumber>3</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_3" FareType="_22">
            <SeatNumber>4</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_2" FareType="_22">
            <SeatNumber>5</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_34" FareType="_23">
            <SeatNumber>6</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_35" FareType="_23">
            <SeatNumber>7</SeatNumber>
        </Ticket>
        <Ticket PassengerID="_36"  FareType="_24">
            <SeatNumber>8</SeatNumber>
        </Ticket>
    </Flight>
    <Department Code="_11" Manager="_7">
        <Name>Passport Control</Name>
    </Department>
    <Department Code="_12" Manager="_7">
        <Name> Check In</Name>
    </Department>
    <Department Code="_13" Manager="_8">
        <Name> Duty Free</Name>
    </Department>
    <Department Code="_14" Manager="_8">
        <Name> Flight</Name>
    </Department>
</Airline>
